This is my small project of quiz game for my python submission
from random import *
print("""Welcom to the quiz game 
would you like to play?  """)
consent = input("-----> ")
consent = consent.lower()
if consent == "no":
    print("The game ends")
    quit()
else:
    print("Be redy to play")
    print("Answer the question in true and false")
points = 0
questions = ["Banana is a vegetable","Two plus two equals to four","Mumbai is the capital of present India","Tiger is an example of bird","punjab is a country"]
store = []
for ii in range(5):
    q1 = choice(questions)
    # q1.append(store)
    print(q1)
    ans1 = input("(True/False)----> ")
    ans1.lower()

    if q1 == questions[0] and ans1 == "false":
        points += 1
    if q1 == questions[1] and ans1 == "true":
        points += 1
    if q1 == questions[2] and ans1 == "false":
        points += 1
    if q1 == questions[3] and ans1 == "false":
        points += 1
    if q1 == questions[4] and ans1 == "false":
        points += 1

    print(f"your points are {points}")
